### ISSUE TITLE
제 생각에는 XOR을 풀었다고 보기 어려울 것 같습니다.

### ISSUE THREAD

**Issue by bzantium** [sunggukcha/xor#2]
1. 만들어주신 문제는 [0,0] -> 0, [0,1] ->1, [1,0] -> 1, [1,1] -> 0 으로 매핑을 시키고 있습니다.

2. 이 문제의 문제는 activation (denoted as f) 을 통과했을 때 if x < 0 or x > 1.6: f(x) = 0 이고 이는 '우연히' 매핑 값인 0과 동일하게 됩니다. 또한 결과 값이 가질 수 있는 값은 [0, 1.6]에 bounded 되며 이 boundary 안에 다른 매핑 값인 1이 존재하고 있습니다.

3. 따라서 이 문제를 조금 바꿔서 [1,1] -> 1, [1,2] -> 2, [2,1] -> 2, [2,2] -> 1 으로 매핑시키는 문제를 풀고자 한다면 제시해주신 솔루션으로는 풀 수 없을 것으로 생각됩니다.

* 제가 틀렸을 수도 있으니 제 말에 오류가 있다면 수정해주세요 :)

**Comment by sunggukcha** [comment]
Thank you for the comment that "ReaLU cannot solve biased linearly non-separable problem, so it is not hard to say that it solves XOR."

I think it depends how we think of 'XOR problem.'

If the 'XOR problem' represents the pure XOR problem, then [1, 1] -> 0, [1, 2] -> 0, ..., in which your problem is not XOR problem. The problem you mentioned is a problem which is similar to XOR in a sense that it is not linearly solvable. Also, I wonder if the perceptron design (Frank Rosenblatt, 1957) is meant to be for the 'biased problem.'
